### ISSUE TITLE
utopia depends on mime-types >= 0

### ISSUE THREAD

**Issue by halostatue** [ioquatix/utopia#1]
I'm preparing mime-types 2.0 for release, and it has some breaking API changes (not for most uses, but some esoteric features). The most important API change is that mime-types 2.0 no longer supports Ruby 1.8.

If this matters, the gemspec needs to be changed from `>= 1.16` to `~> 1.16`.

**Comment by ioquatix** [comment]
This functionality has been revamped.

https://github.com/ioquatix/utopia/blob/14bf541b168f95600d276584625bb1080798c503/lib/utopia/static.rb#L32-L114

It might make sense to merge in something similar to MimeTypeLoader into the mime-types gem.
