### ISSUE TITLE
Bundler 2 error 

### ISSUE THREAD

**Issue by k1tsu** [ioquatix/utopia#18]
Getting error `You must use Bundler 2 or greater with this lockfile.` when running `rake` in a utopia environment.

I tried: 

- Deleting `Gemfile.lock` and executing `sudo bundler install`. (no avail)
- Deleting `Gemfile.lock` and executing `sudo bundle install`. (no avail)

both my `bundle`/`bundler -v` are `2.0.1`

thanks :)

**Comment by ioquatix** [comment]
Did you try running `bundle exec rake`?

**Comment by k1tsu** [comment]
`bundler exec rake` runs, but only runs guard pry. 

```Pierres-Air:site k1tsu$ bundle exec rake
Generating transient session key for development...
09:10:44 - INFO - Guard::RSpec is running
09:10:44 - INFO - Guard is now watching at '/Users/k1tsu/Documents/School/Databasing/k1tsu-Chatbot/site'
[1] guard(main)> ```

**Comment by ioquatix** [comment]
Just prepend bundle exec to whatever you are trying to run and it shouldn't give you any problems. Maybe let me know specifically what you are doing and how it is failing.
